server:
  port: 18010
spring:
  #  国际化
  messages:
    basename: i18n/messages

  application:
    name: example
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  #  数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root.Y4yhljt
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    database: 0

logging:
  level:
    org.springframework: DEBUG
    com.lugew.winsincloud: DEBUG




mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false

winsin:
  enable-mybatis: true
